apps:
  base: "http://localhost:31323"

db:
  uri: postgresql://username:password@host:5432/database?sslmode=disable

interapps:
  proxy:
    tag: latest

irods:
  zone: "cyverse"

k8s:
  frontend:
    base: "https://cyverse.run"

keycloak:
  base: "https://keycloak.example.org/auth"
  realm: "example"
  client-id: "example-client"
  client-secret: "619ba48b-e633-40be-8bb3-8cb7ceb54411"

metadata:
  base: "http://metadata"

path_list:
  file_identifier: "# application/vnd.de.multi-input-path-list+csv; version=1"

resource_tracking:
  bypass_users: []

tickets_path_list:
  file_identifier: "# application/vnd.de.tickets-path-list+csv; version=1"

vice:
  file-transfers:
    image: "discoenv/vice-file-transfers"
    tag: latest
  job-status:
    base: http://job-status-listener
  k8s-enabled: true
  backend-namespace: default
  use_csi_driver: false
  image-pull-secret: ""
  time-limit-extension: "4h"
